### Pricing D'un Call Européen Par L'équation de Black & Scholes par la Méthodes des Différences Finies

**Nous rappelons que l'EDP d'évalution est la suivante:**

<img src="edp.PNG" width="400"/>

Où:
- **σ** : est la volatilité du sous jacent
- **r** : le taux sans risque
- **V(x,t)**: la valeur en t du portefeuille autofinançant de réplication du call
- **S** : le sous-jacent

On note **E** le prix d'exercice (**strike**) du contrat et **T** l'écheance.

**On condiderera les initialisations suivantes:**

**T = 1 an**

**σ = 0.05**

**r = 0.05**

**E = 95**



## Condition Finale d'un Call (C) Européen:
<img src="term.PNG" width="300"/>


## Conditions aux limites:

#### **S appartient à \]0, +oo\[** quelque soit t.
<img src="so.PNG" width="200"/>
<img src="s_inf.PNG" width="250"/>


### Lien entre l’équation de Black-Scholes et l’équation de la chaleur:

**On conisdère dans le cas d'un call l'EDP:
<img src="c_bc.PNG" width="300"/>
Avec les conditions limites et finale ci-haut.**

**On pose les d'abord les changements de variable suivanats**
<img src="chan.PNG" width="400"/>
**L'EDP devient ainsi:**
<img src="edpmod.PNG" width="300"/>
**avec**
<img src="k.PNG" width="100"/>
**la condition finale est transformée en condition initiale suivante:**
<img src="cond.PNG" width="250"/>
**l'intervalle de temps devient:**
<img src="int.PNG" width="100"/>
**le x est dans IR**

**En se basant sur l’équation caractéristique correspondant à l'EDP obtenue précédemment** 
<img src="carac.PNG" width="200"/>
**on fait le changement de variable suivant pour éliminer les opérateur différentiels d'ordre 1 et 0** :
<img src="car.PNG" width="600"/>
**Et**
<img src="beta.PNG" width="300"/>
**Où u est solution de l'Equation de La Chaleur :**
<img src="cha.PNG" width="150"/>
**avec la condition initiale :**
<img src="ini.PNG" width="450"/>

**On voit donc que l’équation de Black-Scholes se ramène à l’équation de la chaleur, qui est plus facile à résoudre (numériquement ou analytiquement)**

**A partir de la solution de l’équation de la chaleur, on remonte à l’équation de Black-Scholes en faisant les changements de variable à l’envers**

## Initialisation des données d'entrée

In [1]:
r = 0.05
E = 95
sigma = 0.1
T=1

In [2]:
k = r/(0.5*sigma*sigma)

In [3]:
print(" k   =   ",k)

 k   =    9.999999999999998


In [4]:
alpha = (1-k)/2
print("alpha   =   ",alpha)

alpha   =    -4.499999999999999


In [5]:
beta = (alpha**2) + (k-1)*alpha - k
print("beta   =   ",beta)

beta   =    -30.249999999999993


# IMPLEMENTATION


#### Etape 1: discrétisation de l'intervalle de temps \[ 0 ; (Tσ^2)/2 \] = \[ 0 ; 0.00125\] en N intervalles constants i.e. t=n.∆t

In [6]:
N = 250
delta_t = ((T*sigma**2)/2)/N
print("delta_t   =    ",delta_t)

delta_t   =     2.0000000000000005e-05


#### Etape 2: Dicrétisation de l'intervalle des espaces.

**Comme théoriquement x est dans IR, on ne pourrait donc pas dicrétiser la droite réelle. On va donc borner les x dans intervalle \[A ; B\]**

**Pour simplifier les calculs et le temps de calcul on borne S dans \[ 35 ; 258\] et comme S=E.exp(x) , x doit être dans l'intervalle: \[Ln(35/E);Ln(258/E)\]**






In [7]:
import math as mt

In [8]:
A = round(mt.log(35/E),2)
B = round(mt.log(258/E),2)
print("A =  ",A,"   B=  ", B)

A =   -1.0    B=   1.0


**Donc on borne x dans \[A;B\] = \[-1 ; 1\]**

#### Choix du pas ∆x :
**d'après la condition de stabilité il faut que: ∆t  ≤  1/2 (∆x)^2 en s'assurant que  ∆x ~ 0 pour que l'erreur de la méthode converge vers 0 ( O((∆x)^2)--->0)**

**(∆x)^2 doit donc être plus grand que 2.∆t**


In [9]:
print( "delta_t x 2   =  ",delta_t*2)

delta_t x 2   =   4.000000000000001e-05


**On prend donc:**

In [10]:
delta_x = 1.265 * mt.sqrt(2*delta_t)
print("delta_x  =   ", delta_x)

delta_x  =    0.008000562480226


**On décompose donc l'intervalle des espaces \[A;B\] = \[-1 ; 1\] en I intervalle avec:** 

In [11]:
I = round((B-A)/delta_x)

print("I   =    ",I)

I   =     250


### Calcul de la stabilité λ  et de la Matrice 
<img src="diag.PNG" width="450"/>

In [12]:
lambda_ = delta_t/(delta_x**2)
print("stabilité lambda   =   ",lambda_)

stabilité lambda   =    0.3124560608664407


**la stabilité est bien inférieur à 1/2 !**

In [13]:
import numpy as np

In [14]:
Matrice=np.zeros((I-2, I-2))

In [15]:
Matrice.shape

(248, 248)

In [16]:
for i in range(Matrice.shape[0]):
    Matrice[i,i]=1-2*lambda_

In [17]:
Matrice

array([[0.37508788, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.37508788, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.37508788, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.37508788, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.37508788,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.37508788]])

In [18]:
for i in range(Matrice.shape[0]):
    for j in range(Matrice.shape[0]):
        if abs(i-j)==1:
            Matrice[i,j]=lambda_

**la matrice est bien construite. Voyons voir les Matrice-Réduite(5,5)**

In [19]:
Matrice[0:5,0:5]

array([[0.37508788, 0.31245606, 0.        , 0.        , 0.        ],
       [0.31245606, 0.37508788, 0.31245606, 0.        , 0.        ],
       [0.        , 0.31245606, 0.37508788, 0.31245606, 0.        ],
       [0.        , 0.        , 0.31245606, 0.37508788, 0.31245606],
       [0.        , 0.        , 0.        , 0.31245606, 0.37508788]])

### Vecteur initial: U(x,0)=U0  x dans \[-1, 1\] discrétisé
<img src="ini.PNG" width="450"/>

#### X est le vecteur contenant la discrétisation de l'intervalle \]-1;1\[

In [20]:
X=np.zeros(Matrice.shape[0])

In [21]:
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [22]:
Zero=X

In [23]:
for i in range(Matrice.shape[0]):
    X[i]=A+delta_x*(i+1)

In [24]:
X

array([-9.91999438e-01, -9.83998875e-01, -9.75998313e-01, -9.67997750e-01,
       -9.59997188e-01, -9.51996625e-01, -9.43996063e-01, -9.35995500e-01,
       -9.27994938e-01, -9.19994375e-01, -9.11993813e-01, -9.03993250e-01,
       -8.95992688e-01, -8.87992125e-01, -8.79991563e-01, -8.71991000e-01,
       -8.63990438e-01, -8.55989875e-01, -8.47989313e-01, -8.39988750e-01,
       -8.31988188e-01, -8.23987625e-01, -8.15987063e-01, -8.07986500e-01,
       -7.99985938e-01, -7.91985376e-01, -7.83984813e-01, -7.75984251e-01,
       -7.67983688e-01, -7.59983126e-01, -7.51982563e-01, -7.43982001e-01,
       -7.35981438e-01, -7.27980876e-01, -7.19980313e-01, -7.11979751e-01,
       -7.03979188e-01, -6.95978626e-01, -6.87978063e-01, -6.79977501e-01,
       -6.71976938e-01, -6.63976376e-01, -6.55975813e-01, -6.47975251e-01,
       -6.39974688e-01, -6.31974126e-01, -6.23973563e-01, -6.15973001e-01,
       -6.07972438e-01, -5.99971876e-01, -5.91971314e-01, -5.83970751e-01,
       -5.75970189e-01, -

#### On déduit donc la valeur U(0,X) en utilisant la fonction Uo(X) énoncée plus haut

In [25]:
U_0=np.exp(0.5*(k+1)*X) - np.exp(0.5*(k-1)*X)

In [26]:
U_0

array([-7.24561811e-03, -7.47566945e-03, -7.71255436e-03, -7.95645135e-03,
       -8.20754230e-03, -8.46601232e-03, -8.73204981e-03, -9.00584634e-03,
       -9.28759669e-03, -9.57749872e-03, -9.87575332e-03, -1.01825644e-02,
       -1.04981386e-02, -1.08226854e-02, -1.11564171e-02, -1.14995483e-02,
       -1.18522960e-02, -1.22148795e-02, -1.25875202e-02, -1.29704411e-02,
       -1.33638672e-02, -1.37680246e-02, -1.41831406e-02, -1.46094435e-02,
       -1.50471620e-02, -1.54965252e-02, -1.59577619e-02, -1.64311005e-02,
       -1.69167684e-02, -1.74149916e-02, -1.79259942e-02, -1.84499981e-02,
       -1.89872220e-02, -1.95378811e-02, -2.01021863e-02, -2.06803437e-02,
       -2.12725537e-02, -2.18790101e-02, -2.24998994e-02, -2.31353999e-02,
       -2.37856806e-02, -2.44509002e-02, -2.51312060e-02, -2.58267326e-02,
       -2.65376010e-02, -2.72639165e-02, -2.80057682e-02, -2.87632267e-02,
       -2.95363428e-02, -3.03251457e-02, -3.11296412e-02, -3.19498096e-02,
       -3.27856040e-02, -

#### On applique cette condition comme on cherche le max entre 0 et les valeurs fournie par la fonction permettant le calcul de U_0

In [27]:
U_0[U_0<0]=0

In [28]:
U_0.shape

(248,)

In [32]:
U_0

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

### Calcul des conditions aux limites \[A;B\] i.e u(-1,τ) et u(1,τ) quelque soit τ dans l'intervalle temporel discrétisé. 

In [33]:
U_A=np.zeros(250)

In [34]:
for i in range(250):
    U_A[i] = np.exp(-alpha*A+beta*(i+1)*delta_t) * ( np.exp(A) - np.exp(-k*(T*0.5*sigma - (i+1)*delta_t)))

In [35]:
U_A

array([-0.00265092, -0.00265066, -0.0026504 , -0.00265015, -0.00264989,
       -0.00264963, -0.00264937, -0.00264911, -0.00264885, -0.00264859,
       -0.00264833, -0.00264807, -0.00264781, -0.00264755, -0.00264729,
       -0.00264702, -0.00264676, -0.0026465 , -0.00264623, -0.00264597,
       -0.00264571, -0.00264544, -0.00264518, -0.00264491, -0.00264465,
       -0.00264438, -0.00264411, -0.00264385, -0.00264358, -0.00264331,
       -0.00264304, -0.00264277, -0.00264251, -0.00264224, -0.00264197,
       -0.0026417 , -0.00264143, -0.00264116, -0.00264088, -0.00264061,
       -0.00264034, -0.00264007, -0.0026398 , -0.00263952, -0.00263925,
       -0.00263898, -0.0026387 , -0.00263843, -0.00263815, -0.00263788,
       -0.0026376 , -0.00263733, -0.00263705, -0.00263677, -0.0026365 ,
       -0.00263622, -0.00263594, -0.00263566, -0.00263539, -0.00263511,
       -0.00263483, -0.00263455, -0.00263427, -0.00263399, -0.00263371,
       -0.00263343, -0.00263314, -0.00263286, -0.00263258, -0.00

In [36]:
U_B=np.zeros(250)

In [37]:
for i in range(250):
    U_B[i] = np.exp(-alpha*B+beta*(i+1)*delta_t)* ( np.exp(B) - np.exp(-k*(T*0.5*sigma - (i+1)*delta_t)))

In [38]:
U_B

array([189.96789616, 189.84209064, 189.71636563, 189.59072108,
       189.46515694, 189.33967315, 189.21426966, 189.08894643,
       188.9637034 , 188.83854053, 188.71345776, 188.58845505,
       188.46353234, 188.33868958, 188.21392672, 188.08924372,
       187.96464052, 187.84011708, 187.71567333, 187.59130924,
       187.46702476, 187.34281982, 187.21869439, 187.09464841,
       186.97068184, 186.84679462, 186.7229867 , 186.59925804,
       186.47560858, 186.35203828, 186.22854708, 186.10513494,
       185.9818018 , 185.85854762, 185.73537235, 185.61227593,
       185.48925832, 185.36631947, 185.24345933, 185.12067785,
       184.99797498, 184.87535067, 184.75280488, 184.63033754,
       184.50794862, 184.38563806, 184.26340582, 184.14125184,
       184.01917608, 183.89717849, 183.77525902, 183.65341762,
       183.53165423, 183.40996882, 183.28836133, 183.16683172,
       183.04537993, 182.92400592, 182.80270963, 182.68149103,
       182.56035005, 182.43928666, 182.31830079, 182.19

In [39]:
M=np.zeros((I-2, N))

In [40]:
M[0,:]=lambda_ * U_A

In [41]:
M[M.shape[0]-1,:] = lambda_ * U_B

In [42]:
M.shape

(248, 250)

In [43]:
M

array([[-8.28295706e-04, -8.28215419e-04, -8.28135009e-04, ...,
        -8.05101942e-04, -8.04995636e-04, -8.04889240e-04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.93566205e+01,  5.93173118e+01,  5.92780283e+01, ...,
         5.03739027e+01,  5.03403514e+01,  5.03068216e+01]])

In [44]:
liste_Solution=[U_0]

In [46]:
liste_Solution

[array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000

In [48]:
M.shape

(248, 250)

## DERNIERE ETAPE: SOLUTION

In [49]:
for i in range(250):
    U=Matrice.dot(U_0)+M[:,i]
    liste_Solution.append(U)
    U_0=U
    

In [50]:
import pandas as pd

In [51]:
liste_Solution=pd.DataFrame(liste_Solution).transpose()

In [52]:
liste_Solution

0           1           2           3           4           5    \
0      0.000000   -0.000828   -0.001139   -0.001336   -0.001471   -0.001571   
1      0.000000    0.000000   -0.000259   -0.000453   -0.000613   -0.000743   
2      0.000000    0.000000    0.000000   -0.000081   -0.000172   -0.000264   
3      0.000000    0.000000    0.000000    0.000000   -0.000025   -0.000063   
4      0.000000    0.000000    0.000000    0.000000    0.000000   -0.000008   
..          ...         ...         ...         ...         ...         ...   
243  115.484043  115.568441  115.652896  115.737408  115.821976  116.033225   
244  121.283499  121.371938  121.460437  121.548996  122.042864  122.737345   
245  127.366001  127.458673  127.551407  128.941186  130.486402  132.038966   
246  133.745095  133.842199  138.090293  141.278762  143.898843  146.034728   
247  140.434964  153.821539  158.833713  162.001778  164.147078  165.731182   

            6           7           8           9    ...         241  \
0     -0.001649   -0.001713   -0.001765   -0.001810  ...   -0.002416   
1     -0.000852   -0.000945   -0.001024   -0.001094  ...   -0.002254   
2     -0.000351   -0.000432   -0.000506   -0.000575  ...   -0.002092   
3     -0.000109   -0.000157   -0.000207   -0.000257  ...   -0.001934   
4     -0.000023   -0.000043   -0.000068   -0.000096  ...   -0.001778   
..          ...         ...         ...         ...  ...         ...   
243  116.354690  116.766470  117.243641  117.765616  ...  138.787692   
244  123.548950  124.412100  125.289551  126.158715  ...  143.802780   
245  133.505679  134.865967  136.117176  137.265503  ...  148.665484   
246  147.815944  149.324267  150.619962  151.746299  ...  153.328947   
247  166.953522  167.929375  168.727533  169.392627  ...  157.745015   

            242         243         244         245         246         247  \
0     -0.002416   -0.002416   -0.002416   -0.002416   -0.002416   -0.002416   
1     -0.002254   -0.002254   -0.002255   -0.002255   -0.002256   -0.002256   
2     -0.002093   -0.002094   -0.002095   -0.002095   -0.002096   -0.002097   
3     -0.001935   -0.001936   -0.001937   -0.001938   -0.001939   -0.001940   
4     -0.001780   -0.001781   -0.001783   -0.001784   -0.001785   -0.001787   
..          ...         ...         ...         ...         ...         ...   
243  138.754132  138.720337  138.686309  138.652051  138.617564  138.582851   
244  143.755167  143.707370  143.659391  143.611232  143.562896  143.514383   
245  148.603230  148.540849  148.478344  148.415715  148.352965  148.290094   
246  153.251647  153.174283  153.096857  153.019368  152.941819  152.864210   
247  157.652465  157.559917  157.467372  157.374829  157.282290  157.189754   

            248         249         250  
0     -0.002416   -0.002416   -0.002416  
1     -0.002256   -0.002257   -0.002257  
2     -0.002098   -0.002098   -0.002099  
3     -0.001941   -0.001942   -0.001943  
4     -0.001788   -0.001789   -0.001791  
..          ...         ...         ...  
243  138.547914  138.512756  138.477378  
244  143.465696  143.416836  143.367806  
245  148.227104  148.163997  148.100774  
246  152.786542  152.708817  152.631034  
247  157.097223  157.004697  156.912175  

[248 rows x 251 columns]

# POUR RETROUVER LES VRAIES VALEURS DU CALL EN TOUT INSTANT ET POUR TOUT S IL SUFFIT DE FAIRE LES CHANGEMENTS DE VARIABLES INVERSES.